plugins {
    id 'application'
}

group = project.group
version = project.version

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}

application {
    mainClass = 'io.github.pentaoa.lodeframe.shaders.LodeframeShaders'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

tasks.named('test') {
    useJUnitPlatform()
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}
